image: harbor.novascotia.ca/cts/devops-cicd:latest

variables:
  REGISTRY_HOST: harbor.novascotia.ca
  ACA_PY_VERSION: py36-1.15-1_0.6.0
  CONTAINER_IMAGE: ${REGISTRY_HOST}/digitalplatformservices/identity/aries-cloudagent-nsds-${ACA_PY_VERSION}:latest


stages:
  - build

build-aries: 
  image: ${REGISTRY_HOST}/cts/dind:latest
  stage: build
  script:
   - echo ${REGISTRY_TOKEN} | docker login -u robot\$GitLab --password-stdin ${REGISTRY_HOST}
   - echo "building ${CONTAINER_IMAGE}"
   - docker build -t ${CONTAINER_IMAGE} . 
   - echo "Pushing to Container Registry ${CONTAINER_IMAGE}"
   - docker push ${CONTAINER_BUILD_IMAGE} 

